{
 "title": "Collection Details",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "collection_id",
    "query": "SELECT id FROM collection_groups WHERE end_date >= NOW() ORDER BY end_date;"
   },
   {
    "name": "collection_type",
    "query": "st : sang,pl : plasma,pt : plaquette"
   },
   {
    "name": "followed_from",
    "query": "SELECT to_char(created_at, 'DD/MM/YYYY') FROM collection_groups WHERE id = [[collection_id]]"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\r\n<h1>\r\nCollecte \r\n<strong>$collection_id</strong> \r\n<small>\r\n(ajouté le \r\n<strong>$followed_from</strong>)\r\n</small>\r\n</h1>\r\n</center>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "collecte",
     "rawSql": "SELECT\r\n  id,\r\n  start_date,\r\n  end_date,\r\n  is_public,\r\n  nature\r\nFROM\r\n  collection_groups "
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT latitude, longitude, full_address FROM locations l\r\nWHERE EXISTS (\r\n  SELECT 1 FROM collection_groups g \r\n  WHERE \r\n    g.id = $collection_id \r\n    AND g.location_id = l.id\r\n)"
    }
   ]
  },
  {
   "title": "Évènements",
   "type": "table",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  id,\r\n  date,\r\n  morning_start_time,\r\n  morning_end_time,\r\n  afternoon_start_time,\r\n  afternoon_end_time\r\nFROM\r\n  collection_events e\r\nWHERE EXISTS (\r\n  SELECT 1 FROM collection_groups g WHERE g.id = $collection_id AND g.id = e.collection_group_id \r\n)"
    }
   ]
  },
  {
   "type": "bargauge",
   "description": "Taux de remplissage",
   "gridPos": { "h": 17, "w": 1, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  s.created_at as time,\r\n  s.taux_remplissage as value\r\nFROM\r\n  collection_groups g\r\nLEFT JOIN\r\n  collection_group_snapshots s\r\nON\r\n  g.id = s.collection_group_id\r\nWHERE\r\n  g.id = $collection_id\r\nORDER BY\r\n  s.created_at"
    }
   ]
  },
  {
   "title": "Status - ${collection_type:value}",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 1, "y": 10 },
   "repeat": "collection_type",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  s.*\r\nFROM \r\n  collection_groups g\r\nLEFT JOIN\r\n  collection_group_snapshots s\r\nON\r\n  g.id = s.collection_group_id\r\nWHERE \r\n  g.id = $collection_id\r\nORDER BY created_at"
    }
   ]
  },
  {
   "title": "Place restantes pour chaque événements",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 18, "x": 6, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  created_at as time,\r\n  total_slots as value,\r\n  CONCAT('Evenement ', event_id)::text as metric\r\nFROM\r\n  schedules s\r\nWHERE EXISTS (\r\n  SELECT 1 from collection_groups g WHERE g.id = $collection_id AND g.efs_id = s.efs_id\r\n)\r\nORDER BY created_at"
    }
   ]
  }
 ]
}