ci:
  skip: [pytest]

default_language_version:
  python: python3.12

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.11
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

# bandit - find common security issues
- repo: https://github.com/pycqa/bandit
  rev: 1.8.6
  hooks:
    - id: bandit
      name: bandit
      exclude: ^tests/
      args:
        - -r
        - collector/collector
        - packages/crawler

- repo: local
  hooks:
    - id: pytest
      name: pytest
      entry: uv run pytest tests --cov=src
      language: system
      types: [python]
      pass_filenames: false