[tool.uv.sources]
api-carto-client = { workspace = true }
crawler = { workspace = true }
collector = { workspace = true }  # Add this

[tool.uv.workspace]
members = [
    "packages/*",
    "collector",  # Add collector to workspace
]

[tool.ruff]
line-length = 120
include = [
    "packages/",
    "collector/cli.py",
    "collector/collector/"
]

[tool.ruff.lint]
select = ["F", "I", "UP"]

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "ruff>=0.12.11",
]
