[project]
name = "crawler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aio-pika>=9.5.5",
    "crawlee[playwright]>=0.6.12",
]

[dependency-groups]
dev = [
    "ruff>=0.12.4",
]
