# Configuration file version
apiVersion: 1

# List of data sources to delete from the database.
deleteDatasources:
  - name: grafana-postgresql-datasource
  - name: loki

# Mark provisioned data sources for deletion if they are no longer in a provisioning file.
# It takes no effect if data sources are already listed in the deleteDatasources section.
prune: true

# List of data sources to insert/update depending on what's
# available in the database.
datasources:
  - name: Postgres
    type: postgres
    access: proxy
    url: $POSTGRES_HOST:$POSTGRES_PORT
    database: $POSTGRES_DB
    user: $POSTGRES_USER
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      sslmode: disable
    isDefault: true
    editable: false
    version: 1

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
    version: 1