{
 "title": "CLI Logs Overview",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "module",
    "query": "locations, collections, schedules"
   }
  ]
 },
 "panels": [
  { "title": "$module", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "module" },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{application=\"collecte-info\"} | json | module = `$module`"
    }
   ]
  },
  {
   "title": "Warnings and Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(message) (count_over_time({application=\"collecte-info\"} | json | level != `INFO` | module = `$module` [1d]))"
    }
   ]
  },
  {
   "title": "Infos",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(message) (count_over_time({application=\"collecte-info\"} | json | level = `INFO` | module = `$module` [1d]))"
    }
   ]
  }
 ]
}