{
 "title": "Event - Details",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "collection_id",
    "query": "SELECT g.id FROM collection_groups g WHERE g.end_date >= NOW()ORDER BY g.start_date;"
   },
   {
    "name": "event_id",
    "query": "SELECT id AS event_id FROM collection_events WHERE collection_group_id = [[collection_id]] ORDER BY date"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1>Évènement <strong>$event_id</strong></h1></center>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT date, timetable_min, timetable_max, event_id, created_at\r\nFROM schedules\r\nWHERE event_id = $event_id\r\nORDER BY date"
    }
   ]
  },
  {
   "type": "bargauge",
   "description": "Taux de remplissage",
   "gridPos": { "h": 16, "w": 1, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  event_id,\r\n  total_slots\r\nFROM \r\n  schedules\r\nWHERE\r\n  event_id = $event_id\r\nORDER BY created_at"
    }
   ]
  },
  {
   "title": "Nombre de places les 7 derniers jours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  created_at,\r\n  total_slots\r\nFROM schedules\r\nWHERE event_id = $event_id AND $__timeFilter(created_at)\r\nORDER BY created_at"
    }
   ]
  },
  {
   "title": "Disponibilité par plage horaire",
   "type": "stat",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "collecte",
     "rawSql": "SELECT created_at as time, timetables\r\nFROM schedules\r\nWHERE event_id = $event_id\r\nORDER BY created_at;"
    }
   ]
  },
  {
   "title": "Places restantes par tranche horaires",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  s.created_at as time,\r\n  js.key::time as schedule,\r\n  js.value as places\r\nFROM\r\n  schedules s, json_each(s.timetables) as js\r\nWHERE\r\n  s.event_id = $event_id \r\nORDER BY created_at;"
    }
   ]
  }
 ]
}