[project]
name = "crawler"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "aio-pika>=9.5.5",
    "beautifulsoup4>=4.13.5",
    "crawlee[playwright]>=0.6.12",
]

[dependency-groups]
dev = [
    "aioresponses>=0.7.8",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.1.0",
    "pytest-cov>=6.2.1",
    "pytest-mock>=3.14.1",
    "ruff>=0.12.4",
]

[tool.setuptools]
packages = ["crawler"]
include-package-data = true

# Add build system
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 120
exclude = [".venv", "storage"]

[tool.ruff.lint]
select = ["F", "I", "UP"]