"""reflect-crawler-changes

Revision ID: 66c2bc90e068
Revises: 4882f4a1012c
Create Date: 2025-09-01 22:13:11.172256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66c2bc90e068'
down_revision: Union[str, Sequence[str], None] = '4882f4a1012c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('location', sa.String(), nullable=True))
    op.alter_column('schedules', 'collecte_type', nullable=False, new_column_name='collect_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('collecte_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('schedules', 'collect_type')
    op.drop_column('schedules', 'location')
    # ### end Alembic commands ###
