{
 "title": "Bad Locations",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "False Lat/Lng",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{application=\"collecte-info\"} |= `LatLng check failed`"
    }
   ]
  },
  {
   "title": "False PostCode",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{application=\"collecte-info\"} |= `PostCode Check failed`"
    }
   ]
  },
  {
   "title": "City",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{application=\"collecte-info\"} |~ `(PostCode Check failed)|(LatLng check failed)`"
    }
   ]
  },
  {
   "title": "PostCode",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{application=\"collecte-info\"} |~ `(PostCode Check failed)|(LatLng check failed)`"
    }
   ]
  }
 ]
}